### ISSUE TITLE
Accessing stubbed functions on Models results in "received value must be a mock or spy function"

### ISSUE THREAD

**Issue by dieterwalckiers** [davesag/sequelize-test-helpers#102]
Hello

I'm integrating sequelize-test-helpers in my unit tests, but I'm having some trouble testing the stubbed functions in the Models.
When I run this test:

```
describe("OptionCategory model", () => {
    const OptionCategory = OptionCategoryFactory(sequelize, dataTypes);
    OptionCategory.associate = ({ OptionKind }) => {
        OptionCategory.belongsTo(OptionKind);
    };
    it('defined a hasMany association with OptionCategory as "optionCategories"', () => {
        console.log("OptionCategory.belongsTo is", OptionCategory.belongsTo); // <-- this returns "spy" !
        expect(OptionCategory.belongsTo).toHaveBeenCalled();
    });
});
```

I get
```
Matcher error: received value must be a mock or spy function

    Received has type:  function
    Received has value: [Function anonymous]
```

Even though OptionCategory.belongsTo prints out as spy. I really don't understand why jest isn't taking it...
This happens with all stubbed functions, by default or by me using sinon.

Here's a link to the test file in my (work in progress) repo, for context:
https://bitbucket.org/dyte/authentic-catalog-api/src/master/tests/unit/models/optionCategory.ts

Thanks a lot for any hints!
Dieter

**Comment by davesag** [comment]
This package is designed to work with `mocha` not `jest`.

**Comment by dieterwalckiers** [comment]
Ok, I got rid of jest completely in favor of mocha, it works now.
I'm relatively new to testing frameworks, and the similar synaxt of jest and mocha made me confuse them with each other.
Thanks a lot for your help!
