### ISSUE TITLE
does sequelize-test-helpers work with jest?

### ISSUE THREAD

**Issue by emclab** [davesag/sequelize-test-helpers#134]
`Prerequisites
This library assumes:

You are using chai — Version 4 or better.
You are using sinon — Version 5 or better.
Using mocha is also recommended, but as long as you are using chai and sinon this should work with any test runner.`

Does sequelize-test-helpers work with jest?

**Comment by davesag** [comment]
@emclab I've not tried it, but if you are using Sinon and Chai then it ought to work with Jest.  Feel free to try it and let me know.

I generally find Jest is better suited to testing front-end code than back end code.
