### ISSUE TITLE
Support for Jest

### ISSUE THREAD

**Issue by imjordanxd** [davesag/sequelize-test-helpers#326]
Jest is a very popular testing framework, are there any plans to support it? Jest is not just for "UI" testing. I'd be keen on using this package in my project to speed up testing.

**Comment by davesag** [comment]
If you take a look at the fork linked off #302 you'll see someone has created a Jest equivalent of this library.  Personally I don't like using Jest for Node projects, though I do use it extensively for React projects where it shines.  In Node projects I find Jest to be too limiting in terms of splitting out unit vs integration testing, whereas Mocha excels at that.
