### ISSUE TITLE
checking unique and non-unique indexes

### ISSUE THREAD

**Issue by rconstantine** [davesag/sequelize-test-helpers#345]
I have tried to check both unique and non-unique indexes as below:

```javascript
    describe('unique indexes', () => {
        ;['username'].forEach(checkUniqueIndex(group))
    });

    describe('non-unique indexes', () => {
        ;['displayName'].forEach(checkNonUniqueIndex(group))
    });
```

I also tried the below:

```javascript
    describe('indexes', () => {
        ;['username'].forEach(checkUniqueIndex(group))
        ;['displayName'].forEach(checkNonUniqueIndex(group))
    });
```
The error I get in either case is: "indexed a non-unique displayName"

What am I doing wrong?

**Comment by davesag** [comment]
Thanks for reporting this @rconstantine I'll take a look.

**Comment by davesag** [comment]
Could you please supply the model you are testing in this case so I can see how the indexes are being defined.

I'll harden up the testing of the `checks` in the meantime.

The model being tested in the unit tests is

```js
const model = (sequelize, DataTypes) => {
  const Indexed = sequelize.define(
    'Indexed',
    {
      name: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
          notEmpty: true
        }
      },
      lunch: DataTypes.STRING,
      uuid: DataTypes.UUID
    },
    {
      indexes: [
        { unique: true, fields: ['uuid'] },
        { unique: false, fields: ['name'] },
        { unique: true, fields: ['name', 'lunch'] }
      ]
    }
  )

  return Indexed
}

module.exports = model
```

**Comment by davesag** [comment]
I've hardened up the testing of the indexes and cleaned up some of that code, and also now allow for checking of unique or non-unique composite index keys - see PR #346 

This has been released as version `1.4.0` - please update and see if the issue continues.

And please supply a simple example of the Model you are trying to test.

**Comment by rconstantine** [comment]
Perhaps I simply need to add the unique: false to those indices that are false. I'll try that. As for compound indices, I must be calling the function incorrectly. Below is the code I'm using (with another model) to check unique compound indices, and below that the model with the unique and non-unique indices. Thanks for looking.

```javascript
describe('unique compound indexes', () => {
        ;['report_id', 'user_id'].forEach(checkUniqueCompoundIndex(myReports))
        // ;['displayName', 'company'].forEach(checkNonUniqueIndex(user))
    });
```

I must be passing the above incorrectly. I get an error stating " indecies.join is not a function" Note the word "indices" is misspelled. ;)

```javascript
import Sequelize from 'sequelize'

export default(seq) => {
  return seq.define('user', {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    username: {
      type: Sequelize.STRING(50),
      unique: true,
      allowNull: false
    },
    displayName: {
      type: Sequelize.STRING(50),
      unique: false,
      allowNull: false
    },
    office: {
      type: Sequelize.STRING,
      unique: false,
      allowNull: true
    },
    company: {
      type: Sequelize.STRING,
      unique: false,
      allowNull: false
    },
    department: {
      type: Sequelize.STRING,
      allowNull: false
    },
    mail: {
      type: Sequelize.STRING,
      allowNull: true,
      defaultValue: null,
      validate: {
        isEmail: true
      }
    },
    mobile: {
      type: Sequelize.STRING,
      allowNull: true,
      defaultValue: null
    },
    directReports: {
      type: Sequelize.TEXT,
      allowNull: true,
      defaultValue: null
    },
    active: {
      type: Sequelize.BOOLEAN,
      defaultValue: true
    }
  }, {
    indexes: [
      {
        unique: true,
        fields: ['username']
      },
      {
        fields: ['displayName']
      },
      {
        fields: ['company']
      }
    ]
  })
}
```

**Comment by rconstantine** [comment]
My bad. Double square brackets. I should have guessed. Otherwise, how else to do multiple sets? I don't think I have any, but can a compound index have 3 or more fields? Thanks for the help!

**Comment by davesag** [comment]
Hey @rconstantine yes you need to specify `unique: false` - tho that said I should probably check to see what the default is and adjust the check accordingly.

To check for compound indexes simply pass in an array of field names to either `checkUniqueIndex` or `checkNonUniqueIndex` as needed.

```js
describe('unique compound indexes', () => {
     ;[['report_id', 'user_id']].forEach(checkUniqueIndex(myReports))
 });
```

**Comment by davesag** [comment]
@rconstantine if you use version 1.4.1 (released just now) you don't need to specify `unique: false` any more. - See issue #348 and PR #349

**Comment by rconstantine** [comment]
Thanks a bunch.
