### ISSUE TITLE
No TypeScript type definitions

### ISSUE THREAD

**Issue by wyqydsyq** [davesag/sequelize-test-helpers#53]
Project needs tome typedefs, if anyone has written some they'd like to share would be great, otherwise I'll PR whatever I come up with

**Comment by davesag** [comment]
I'm not a typescript user myself but feel free to fork and create a PR and I'll certainly take a look at it.

**Comment by davesag** [comment]
Closing this as clearly no-one else cares about typedefs either.

**Comment by siemah** [comment]
Hey @wyqydsyq, i suppose you're using typescript, if so you can create a `type definitions` as follow:
 
- create `typings/` directory in you root directory
- inside of `typings/` create new file with the name of module in this case `sequelize-test-helpers` with `.d.ts` as extension
- add this code 
```ts
declare module "sequelize-test-helpers";
```
- or define each function and variable in that file

I hope will help you

**Comment by davesag** [comment]
Honestly if anyone wants to add typescript definitions, and can show a way of testing those definitions so I can know they are correct, and make a PR, I'll happily include them in the project.  I'm not anti-typescript type definitions but by the same token I don't do typescript myself.

Really the typescript definitions for the mocks ought to be identical to any typescript definitions for the actual request and response functions that Express defines.

- https://expressjs.com/en/api.html#req
- https://expressjs.com/en/api.html#res
