### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [davesag/sequelize-test-helpers#86]
Hi again @davesag I've reviewed your pinned repositories. i found a logo idea for this repo. What do you think?

![sq](https://user-images.githubusercontent.com/36298335/56893145-625ffe00-6a8a-11e9-86c8-325a961759e8.jpg)

**Comment by davesag** [comment]
Hi @reallinfo that's cool and I like the concept.

Feedback

1. The perspective seems slightly out to my eye.  Maybe drop the top corner slightly.
2. I think you could choose a better typeface.

Cheers and thanks

D

**Comment by reallinfo** [comment]
Yeah, you are right. Thanks for feedback. I made a few changes. How does it look?

![sq2](https://user-images.githubusercontent.com/36298335/56895242-2b411b00-6a91-11e9-8fb2-812c106b98a3.jpg)

**Comment by davesag** [comment]
I like the new lower-case font.

To my eye the perspective still looks off.  I've hacked it slightly - see below.

![logo-tweaks](https://user-images.githubusercontent.com/387098/56896575-b3cbb580-6aa9-11e9-9637-a8ba2ebc5370.png)

Not perfect but sorry I am on my phone.

**Comment by reallinfo** [comment]
Sorry, I don't understand what you're talking about ''slightly?'' 

- Are you talking about the corners?
- colors of the cube?
- tool color?

Is there the variation you prefer in the following image?

![1](https://user-images.githubusercontent.com/36298335/56918454-c3a5c280-6ac6-11e9-85be-5156425659e9.jpg)

**Comment by davesag** [comment]
The top point is too high.  That's what I hacked.  I just chopped some of the image off the top edges to fix the perspective.  I like the rounded corners but they are not so reminiscent of sequelize. maybe keep the hard corners but just fix the perspective (pull the top point down a bit).

**Comment by reallinfo** [comment]
Oh okay, i understand now. I made changes.

![1](https://user-images.githubusercontent.com/36298335/56958701-b4b92180-6b53-11e9-9cbd-faf0ead1b858.jpg)

**Comment by davesag** [comment]
That's cool.  Could that top point come up just a tiny bit?  Then could I have it as an SVG with the wording all in one line?

**Comment by reallinfo** [comment]
I made changes.  I've uploaded all svg variations here. You can check it here.

https://drive.google.com/open?id=1mY3j3ZXKiWDMeCod4KedHLEMFpvQX1hA

**Comment by davesag** [comment]
Thanks @reallinfo — I have added the logo. I have also added a thanks to you at the bottom of the readme. Cheers D

**Comment by reallinfo** [comment]
You're welcome. I will review your other pinned repos. If I get an idea, see you. Thanks!

**Comment by davesag** [comment]
You could do a similar one for [`sequelize-pg-utils`](https://github.com/davesag/sequelize-pg-utilities)
